travis:
  secure:
    BINSTAR_TOKEN: vVcYXsi8ww4kKGZvqy93hHJo+uRPfYPrgVNAxSOkahvQQ6w+1GOmQpYYEbvHJmJQQ58hvTZBxNl/dTVWDyn0C/+Re/U3Q+TLmje+RVk37l6TVt/Hq9LBPuaAWsX7otbpRqfwrnLESRSSuQiutAxA1P2VJ7NGL4/K52q6VtedCWMsMUP+WKgQ7OdYCLE0ZZgstWdTsKhdq4HoPG6pape9TGdUggKHoy2HhUEGy9SGdaiOpyH8keCK0qRtL9aeWT2rDK6Bo+gy0cNjV4ndpEdNO4pE8Poj2pJaWS+CkmIKSq6k042a19sfN8ZTESSPoFoi3wE/88VzOTwO/Bw9dm6XVrB7ahdnRm5Arsx5bGqQ3bYxj1npKDyHS1bFqy+ucEZ8+FfhZf1Gky3nzd3/BcS6byLo43PorUj/BJsUpMdYp0PZItIlnrlrU5Kh1RRJZi9iYVCBTpreV2deTqjkd/vnIlXxrilLJ/uFNoBCE57HlZlUHLhLRvs3oLm4uw4LbFu2im3ijiIlaZZIs5Y50GIFxQ4jUXKNPHnK3Vmx5KoaOuSr3dhvHo1vMKO4xJ5qyRYlbinxYpNxpTpIeOcVeH0/eLpp/5fn9si8M0T/P/gu9H9ttYll/Zf48g8JmI5q7zhVcZcsqqAXIsCOo9Y9ej6FR8N0OFkIcMzv6t5/YC1WMO0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
